version: "3.8"
services:
  mongo-db:
    image: mongo:5.0
    container_name: mongoDB
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongoadmin 
      MONGO_INITDB_ROOT_PASSWORD: mongopasswd  
    volumes: 
      - mymongodata:/data/db

volumes:
  mymongodata: